name: yonder
version: 0.0.1-dev
description: In-memory object database for app model management in Flutter apps.
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: '>=1.0.0 <2.0.0'
  quiver: ^2.0.1
dev_dependencies:
  path: '>=1.0.0 <2.0.0'
  test: '>=1.2.0 <2.0.0'
  built_collection: ^4.0.0
  built_value: ^6.0.0
